//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSR_Gadget.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSR_Gadget.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 Shaved
        ///1100 Receding
        ///1200 Short
        ///1300 Swept Back
        ///1400 Ponytail
        ///1500 Wild
        ///1600 Parted Center
        ///1700 Semi-Long
        ///1800 Curly
        ///1900 Bobbed
        ///2000 Male 11
        ///2100 Male 12
        ///2200 Male 13
        ///2300 Male 14
        ///2400 Male 15
        ///2500 Male 16
        ///2600 Male 17
        ///2700 Male 18
        ///2800 Male 19
        ///2900 Male 20
        ///3000 Shaved
        ///3100 Very Short
        ///3200 Wave
        ///3300 Straight A
        ///3400 Straight B
        ///3500 Ponytail A
        ///3600 Ponytail B
        ///3700 Pigtails
        ///3800 Bun
        ///3900 Braided
        ///4000 Female 11
        ///4100 Female 12
        ///4200 Female 13
        ///4300 Female 14
        ///4400 Female 15
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllProtectors {
            get {
                return ResourceManager.GetString("AllProtectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1 None
        ///100000 Dagger
        ///100001 Dagger+1
        ///100002 Dagger+2
        ///100003 Dagger+3
        ///100004 Dagger+4
        ///100005 Dagger+5
        ///100006 Dagger+6
        ///100007 Dagger+7
        ///100008 Dagger+8
        ///100009 Dagger+9
        ///100010 Dagger+10
        ///100011 Dagger+11
        ///100012 Dagger+12
        ///100013 Dagger+13
        ///100014 Dagger+14
        ///100015 Dagger+15
        ///100100 Crystal Dagger
        ///100101 Crystal Dagger+1
        ///100102 Crystal Dagger+2
        ///100103 Crystal Dagger+3
        ///100104 Crystal Dagger+4
        ///100105 Crystal Dagger+5
        ///100200 Lightning Dagger
        ///100201 Lightning Dagger+1
        ///100202 Lightning Dagger+2
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllWeapons {
            get {
                return ResourceManager.GetString("AllWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100000 Depths #1 (beginning of level)
        ///100001 Depths #2 (near bonfire key)
        ///100010 Depths #3 (near channeler)
        ///100011 Depths #4 (blighttown door)
        ///101000 Undead Burg #1 (outside sewer)
        ///101010 Undead Burg #2 (outside bonfire)
        ///101011 Undead Burg #3 (taurus fog gate)
        ///101100 Lower Undead Burg #1 (near ladder entrance)
        ///101101 Lower Undead Burg #2 (capra fog gate)
        ///101200 Undead Parish #1 (dragon bridge)
        ///101210 Undead Parish #2 (gargoyle fog gate)
        ///102000 Firelink Shrine #1
        ///110000 Painted World of Ariamis # [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:  48 b9 fe fe fe fe fe    movabs rcx,0xfefefefefefefefe
        ///7:  fe fe fe
        ///a:  48 8b 09                mov    rcx,QWORD PTR [rcx]
        ///d:  ba 01 00 00 00          mov    edx,0x1
        ///12: 48 83 ec 38             sub    rsp,0x38
        ///16: 49 be fe fe fe fe fe    movabs r14,0xfefefefefefefefe
        ///1d: fe fe fe
        ///20: 41 ff d6                call   r14
        ///23: 48 83 c4 38             add    rsp,0x38
        ///27: c3                      ret .
        /// </summary>
        internal static string BonfireWarp {
            get {
                return ResourceManager.GetString("BonfireWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 None
        ///2 Point Forward
        ///4 Point Up
        ///6 Point Down
        ///8 Beckon
        ///10 Wave
        ///12 Bow
        ///14 Proper Bow
        ///16 Hurrah!
        ///18 Joy
        ///20 Shrug
        ///22 Look skyward
        ///24 Well! What is it!
        ///26 Prostration
        ///28 Prayer
        ///30 Praise The Sun.
        /// </summary>
        internal static string Gestures {
            get {
                return ResourceManager.GetString("Gestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:  ba fe fe fe fe          mov    edx,0xfefefefe
        ///5:  41 b9 fe fe fe fe       mov    r9d,0xfefefefe
        ///b:  41 b8 fe fe fe fe       mov    r8d,0xfefefefe
        ///11: 41 bc fe fe fe fe       mov    r12d,0xfefefefe
        ///17: 48 a1 fe fe fe fe fe    movabs rax,ds:0xfefefefefefefefe
        ///1e: fe fe fe
        ///21: c6 44 24 38 01          mov    BYTE PTR [rsp+0x38],0x1
        ///26: 40 88 7c 24 30          mov    BYTE PTR [rsp+0x30],dil
        ///2b: c6 44 24 28 01          mov    BYTE PTR [rsp+0x28],0x1
        ///30: 4c 8b 78 10             mov    r15,QWORD PTR [r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItem {
            get {
                return ResourceManager.GetString("GetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 None
        ///1 White Summon
        ///2 Red Summon
        ///3 Red Invade
        ///7 Gravelord Invade
        ///10 Dragon Summon
        ///11 Darkmoon Invade
        ///12 Arena (1v1)
        ///13 Arena (1v1)
        ///14 Arena (Team)
        ///15 Arena (Team)
        ///16 Arena (Team)
        ///17 Arena (Team)
        ///18 Arena (Team)
        ///19 Arena (Team)
        ///20 Arena (FFA)
        ///21 Arena (FFA)
        ///22 Arena (FFA)
        ///23 Arena (FFA)
        ///24 Arena (FFA)
        ///25 Arena (FFA).
        /// </summary>
        internal static string Invasions {
            get {
                return ResourceManager.GetString("Invasions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:  ba fe fe fe fe          mov    edx,0xfefefefe
        ///5:  41 b8 01 00 00 00       mov    r8d,0x1
        ///b:  48 83 ec 38             sub    rsp,0x38
        ///f:  49 be 70 db 6e 40 01    movabs r14,0x1406edb70
        ///16: 00 00 00
        ///19: 41 ff d6                call   r14
        ///1c: 48 83 c4 38             add    rsp,0x38
        ///20: c3                      ret .
        /// </summary>
        internal static string KickPlayer {
            get {
                return ResourceManager.GetString("KickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:  48 b9 70 a3 d1 41 01    movabs rcx,0x141d1a370
        ///7:  00 00 00
        ///a:  48 8b 09                mov    rcx,QWORD PTR [rcx]
        ///d:  48 83 ec 38             sub    rsp,0x38
        ///11: 49 be 40 94 50 40 01    movabs r14,0x140509440
        ///18: 00 00 00
        ///1b: 41 ff d6                call   r14
        ///1e: 48 83 c4 38             add    rsp,0x38
        ///22: c3                      ret .
        /// </summary>
        internal static string LeaveSession {
            get {
                return ResourceManager.GetString("LeaveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:  48 ba 00 00 00 00 ff    movabs rdx,0xffffffff00000000
        ///7:  ff ff ff
        ///a:  48 b9 00 00 00 00 ff    movabs rcx,0xffffffff00000000
        ///11: ff ff ff
        ///14: 48 83 ec 38             sub    rsp,0x38
        ///18: 49 be 20 99 68 40 01    movabs r14,0x140689920
        ///1f: 00 00 00
        ///22: 41 ff d6                call   r14
        ///25: 48 83 c4 38             add    rsp,0x38
        ///29: c3                      ret .
        /// </summary>
        internal static string LevelUp {
            get {
                return ResourceManager.GetString("LevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1 0 None
        ///3000 90 Soul Arrow
        ///3010 60 Great Souls Arrow
        ///3020 36 Heavy Souls Arrow
        ///3030 24 Great Heavy Souls Arrow
        ///3040 30 Homing Soulsmass
        ///3050 30 Homing Crystal Soulsmass
        ///3060 12 Souls Spear
        ///3070 12 Crystal Souls Spear
        ///3100 15 Magic Weapon
        ///3110 9 Great Magic Weapon
        ///3120 9 Crystal Magic Weapon
        ///3300 15 Magic Shield
        ///3310 9 Strong Magic Shield
        ///3400 9 Hidden Weapon
        ///3410 9 Hidden Body
        ///3500 9 Cast Light
        ///3510 18 Hush
        ///3520 60 Aural Decoy
        ///3530 3 Repair
        ///3540 30 Fall Control
        ///3550 33 Chameleon
        ///3600 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Magic {
            get {
                return ResourceManager.GetString("Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 White Phantom
        ///1 Black Phantom (Invade)
        ///2 Black Phantom
        ///3 Dragon Spirit
        ///4 White Phantom
        ///5 Black Phantom (Team)
        ///6 Summon Gravelord phantom
        ///7 Never Connects
        ///8 Instant DC (InvadeType 8) (ttype 17, chrtype 2)
        ///8 Instant DC (InvadeType 9) (ttype 17, chrtype 2)
        ///10 Summon Dragon Spirit (Instant DC?)
        ///11 Invade Darkmoon (Instant DC?)
        ///12 Arena (FFA)
        ///13 Arena (FFA) (ttype 16, chrtype 13)
        ///14 Arena (Team 1)
        ///15 Arena (Team 1)
        ///16 Arena (Team 1)
        ///17 Arena (Team 2)
        ///18 Arena (Team 2)
        ///19 Arena (Team 2)
        ///20 A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Summons {
            get {
                return ResourceManager.GetString("Summons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:  48 89 1d 0b 00 00 00    mov    QWORD PTR [rip+0xb],rbx
        ///7:  48 8b 03                mov    rax,QWORD PTR [rbx]
        ///a:  48 89 d9                mov    rcx,rbx
        ///d:  e9 00 00 00 00          jmp    12 &lt;_main+0x12&gt; .
        /// </summary>
        internal static string TargetedEntity {
            get {
                return ResourceManager.GetString("TargetedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 1 Human
        ///8 4 Hollow
        ///1 2 White Phantom
        ///2 16 Red Phantom
        ///2 17 Blue Phantom
        ///2 18 Path of the Dragon
        ///13 16 Arena FFA
        ///13 17 Arena Team 1
        ///13 18 Arena Team 2
        ///2 3 Red Phantom (Team).
        /// </summary>
        internal static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
    }
}
